bag/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

velvet_goldmine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6,
                                        decimal_places=2,
                                        null=False, default=0)
    order_total = models.DecimalField(max_digits=10,
                                      decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10,
                                      decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0

        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (self.order_total *
                                  settings.STANDARD_DELIVERY_PERCENTAGE
                                  / 100)
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True,
                                    blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,
                            default='', unique=True, null=False)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

    def get_absolute_url(self):
        kwargs = {
            'category_slug': self.slug,
            }
        return reverse('product_categories', kwargs=kwargs)


class Subcategory(models.Model):

    class Meta:
        verbose_name_plural = 'Subcategories'

    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,
                            default='', unique=True, null=False)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

    def get_absolute_url(self):
        kwargs = {
            'subcategory_slug': self.slug
            }
        return reverse('product_subcategories',
                       kwargs=kwargs)


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    subcategory = models.ForeignKey('Subcategory', null=True, blank=True,
                                    on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254,
                            default='', unique=True, null=False)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        kwargs = {
            'product_slug': self.slug,
        }
        return reverse('product_detail', kwargs=kwargs)

products/forms.py
from django import forms
from .models import Product, Category
from .widgets import CustomClearableFileInput


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'rounded-0 input-shadow'

products/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, Subcategory
from .forms import ProductForm


def all_products(request):
    """ A view to show all products, including sorting and searching """

    products = Product.objects.all()
    query = None
    categories = None
    subcategories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if sortkey == 'subcategory':
                sortkey = 'subcategory__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)
            subcategories = Subcategory.objects.filter(category__in=categories)

        if 'subcategory' in request.GET:
            subcategories = request.GET['subcategory'].split(',')
            products = products.filter(subcategory__name__in=subcategories)
            subcategories = Subcategory.objects.filter(name__in=subcategories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               ("You didn't enter any search criteria!"))
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                                                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_subcategories': subcategories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """A view to show individual product details"""

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


# def favourite_product(request, product_id):
#     product = get_object_or_404(Product, pk=product_id)
#     if product.favourite.objects.filter(id=request.user.id).exists():
#         product.favourite.remove(request.user)
#     else:
#         product.favourite.add(request.user)

#     return redirect(reverse('product_detail', args=[product.id]))


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, f'Successfully added {product.name}!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request,
                           'Failed to add product.'
                           'Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'

    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, f'Successfully updated {product.name}!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, f'Failed to update {product.name}.\
                                     Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f'{product.name} deleted!')
    return redirect(reverse('products'))

products/templates/products/includes/breadcrumbs.html
{% if product %}
    <small>
        <nav aria-label="breadcrumb" class="product-breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'products' %}">All Products</a></li>
                {% if product.category.name == 'dresses' or product.category.name == 'bottoms' or product.category.name == 'tops_ts' or product.category.name == 'outerwear'%}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category=dresses,bottoms,tops_ts,outerwear">All Clothing</a></li> 
                {% endif %}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category={{ product.category.name }}">{{product.category.friendly_name}}</a></li>
                {% if product.subcategory %}
                {% if product.subcategory.name == 'earrings' or product.subcategory.name == 'bracelets' or product.subcategory.name == 'necklaces' %}  
                <li class="breadcrumb-item"><a href="{% url 'products' %}?subcategory=earrings,necklaces,bracelets">Jewellery</a></li> 
                <li class="breadcrumb-item"><a href="{% url 'products' %}?subcategory={{ product.subcategory.name }}">{{product.subcategory.friendly_name}}</a></li>
                {% else %}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?subcategory={{ product.subcategory.name }}">{{product.subcategory.friendly_name}}</a></li>
                {% endif %}
                {% endif %}
                <li class="breadcrumb-item">{{product.name}}</li>
            </ol>
        </nav>
    </small>
{% endif %}


{% if current_categories %}
    <small>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
        {% for category in current_categories|slice:":1" %} 
                <li class="breadcrumb-item"><a href="{% url 'products' %}">All Products</a></li> 
            
            {% if current_categories|length > 1 %}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category=dresses,bottoms,tops_ts,outerwear">All Clothing</a></li> 
            {% elif current_categories|length == 1 and category.name == 'dresses' or category.name == 'bottoms' or category.name == 'tops_ts' or category.name == 'outerwear' %}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category=dresses,bottoms,tops_ts,outerwear">All Clothing</a></li>
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category={{category.name}}">{{category.friendly_name}}</a></li>   
            {% elif current_categories|length == 1 and category.name != 'dresses' or category.name != 'bottoms' or category.name != 'tops_ts' or category.name != 'outwear'%}
                <li class="breadcrumb-item"><a href="{% url 'products' %}?category={{category.name}}">{{category.friendly_name}}</a></li>
            {% endif %}
        {% endfor %}
              
            </ol>
        </nav>
    </small>

{% else %}

    <small>
        <nav>
            <ol class="breadcrumb">
            {% if not product %}
                <li class="breadcrumb-item"><a href="{% url 'products' %}">All Products</a></li>
                {% if current_subcategories %}
                    {% for subcategory in current_subcategories|slice:":1" %}
                        {% if subcategory.category.name == 'dresses' or subcategory.category.name == 'tops_ts' or subcategory.category.name == 'bottoms' %}  
                            <li class="breadcrumb-item"><a href="{% url 'products' %}?category=dresses,bottoms,tops_ts,outerwear">All Clothing</a></li>
                        {% endif %}
                            <li class="breadcrumb-item"><a href="{% url 'products' %}?category={{subcategory.category.name}}">{{subcategory.category.friendly_name}}</a></li>
                     
                        {% if current_subcategories|length > 1 and subcategory.category.name == 'accessories'  %}  
                            <li class="breadcrumb-item"><a href="{% url 'products' %}?subcategory=earrings,necklaces,bracelets">Jewellery</a></li> 
                        {% endif %}
                        
                        {% if current_subcategories|length == 1 %}
                        {% if subcategory.name == 'earrings' or subcategory.name == 'bracelets' or subcategory.name == 'necklaces' %}  
                            <li class="breadcrumb-item"><a href="{% url 'products' %}?subcategory=earrings,necklaces,bracelets">Jewellery</a></li> 
                            <li class="breadcrumb-item" aria-current="page">{{subcategory.friendly_name}}</li>
                         {% else %}
                            <li class="breadcrumb-item" aria-current="page">{{subcategory.friendly_name}}</li>
                        {% endif %}
                        {% endif %} 
                    {% endfor %}
                {% endif %}
            {% endif %}
            </ol>       
        </nav>
    </small>
{% endif %}

products/templates/products/includes/qty_input_script.html
<script type="text/javascript">

// Disable +/- buttons outside 1-99 range
    function handleEnableDisableBtns(itemId) {
        let currentValue = parseInt($(`#id_qty_${itemId}`).val());
        let minusDisabled = currentValue < 2;
        let plusDisabled = currentValue > 98;
        $(`#decrement-qty_${itemId}`).prop('disabled', minusDisabled);
        $(`#increment-qty_${itemId}`).prop('disabled', plusDisabled);
    }

// Ensure proper enabling/disabling of all inputs on page load
    let allQtyInputs = $('.qty_input');
    for(let i = 0; i < allQtyInputs.length; i++){
        let itemId = $(allQtyInputs[i]).data('item_id');
        handleEnableDisableBtns(itemId);
    }

 // Check enable/disable every time the input is changed
    $('.qty_input').change(function() {
        let itemId = $(this).data('item_id');
        handleEnableDisableBtns(itemId);
    });

// Increment Qty
    $('.increment-qty').click(function(e) {
        e.preventDefault();
        let closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        let currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue + 1);
        let itemId = $(this).data('item_id');
        handleEnableDisableBtns(itemId);
    });

// Decrement Qty
    $('.decrement-qty').click(function(e) {
        e.preventDefault();
        let closestInput = $(this).closest('.input-group').find('.qty_input')[0];
        let currentValue = parseInt($(closestInput).val());
        $(closestInput).val(currentValue - 1);
        let itemId = $(this).data('item_id');
        handleEnableDisableBtns(itemId)
    });

</script>

products/templates/products/includes/random_carousel.html
<div class="rand-carousel-container d-none d-md-block">
    <div class="random-carousel" data-flickity='{ "wrapAround": true, "autoPlay": true, "cellAlign": "left", "contain": true }'>
        {% for product in rand_products %}
        <div class="carousel-cell-random">
            <div>
                {% if product.image %}
                <a href="{% url 'product_detail' product.id %}">
                    <img class="card-img-top img-fluid carousel-img-random" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="{% url 'product_detail' product.id %}">
                    <img class="card-img-top img-fluid carousel-img-random" src="{{ MEDIA_URL }}no_image.png" alt="{{ product.name }}">
                </a>
                {% endif %}
                    <p class="mb-0 text-center">{{ product.name }}</p>
                    <p class="mb-0 text-center">€{{ product.price }}</p>  
            </div>
        </div>
        {% endfor %}  
    </div>   
</div>

products/templates/products/includes/sizes.html
{% if product.category.name == 'footwear' %}
    <div class="col-12 text-pink text-center mb-2">
      <strong>select size:</strong>
         <select class="form-control w-50 m-auto text-pink" name="product_size" id="id_product_size">
           <option class="text-pink" value="3">3</option>
           <option class="text-pink" value="4">4</option>
           <option class="text-pink" value="5" selected>5</option>
           <option class="text-pink" value="6">6</option>
           <option class="text-pink" value="7">7</option>
         </select>
        <small> sizes are UK sizes</small>
     </div>
{% endif %}

{% if product.category.name != 'footwear' and product.category.name != 'accessories' %}
    <div class="col-12 text-pink text-center mb-2">
       <p><strong>select size:</strong> </p>
         <select class="form-control w-50 m-auto text-pink" name="product_size" id="id_product_size">
           <option class="text-pink" value="4">4</option>
           <option class="text-pink" value="6">6</option>
           <option class="text-pink" value="8" selected>8</option>
           <option class="text-pink" value="10">10</option>
           <option class="text-pink" value="12">12</option>
           <option class="text-pink" value="14">14</option>
           <option class="text-pink" value="16">16</option>
           <option class="text-pink" value="18">18</option>
         </select>
        <small> sizes are UK sizes</small>
     </div>
{% endif %}